apiVersion: apps/v1
kind: Deployment
metadata:
  name: vb-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: vb
  template:
    metadata:
      labels:
        app: vb
    spec:
      containers:
      - name: vb
        image: dinu7031/vb:latest
        ports:
        - containerPort: 8000 # Port your application listens on

 apiVersion: v1
kind: Service
metadata:
  name: vb-service
spec:
  selector:
    app: vb
  ports:
    - protocol: TCP
      port: 88  # Port exposed by the service externally (outside the cluster)
      targetPort: 8000  # Port your application listens on inside the pods
  type: LoadBalancer
