apiVersion: v1
kind: Service
metadata:
  name: vb-service
spec:
  selector:
    app: vb
  ports:
    - protocol: TCP
      port: 88  # Port exposed by the service externally (outside the cluster)
      targetPort: 8000  # Port your application listens on inside the pods
  type: LoadBalancer
